/**
 * data.ts — Dados estáticos da campanha
 * Copiados fielmente do HTML original.
 */

export const DONATION_VALUES = [30, 50, 70, 100, 150, 200, 300, 500];

export const FAKE_DONATION_QUEUE = [
  { name: 'Anônimo', amount: 30 },
  { name: 'Anônimo', amount: 75 },
  { name: 'Anônimo', amount: 100 },
  { name: 'Anônimo', amount: 60 },
  { name: 'Anônimo', amount: 150 },
  { name: 'Anônimo', amount: 80 },
  { name: 'Anônimo', amount: 50 },
  { name: 'Anônimo', amount: 120 },
  { name: 'Anônimo', amount: 90 },
  { name: 'Anônimo', amount: 75 },
];

export const DONOR_LIST = [
  { name: 'Anônimo', time: 'há 15 minutos', amount: 'R$ 20,00' },
  { name: 'Leandro Santos da Silva', time: 'há 2 horas', amount: 'R$ 10,00' },
  { name: 'Suzana Coral dos Santos', time: 'há 5 horas', amount: 'R$ 25,00' },
  { name: 'Leonardo', time: 'há 1 dia', amount: 'R$ 30,00' },
  { name: 'Anônimo', time: 'há 1 dia', amount: 'R$ 30,00' },
  { name: 'Aline De Mendonça Silva', time: 'há 2 dias', amount: 'R$ 50,00' },
  { name: 'Anônimo', time: 'há 3 dias', amount: 'R$ 30,00' },
  { name: 'Isabela Pires', time: 'há 4 dias', amount: 'R$ 30,00' },
  { name: 'Renata Cavallini', time: 'há 8 horas', amount: 'R$ 10,00' },
  { name: 'Anônimo', time: 'há 30 minutos', amount: 'R$ 25,00' },
  { name: 'Anônimo', time: 'há 6 dias', amount: 'R$ 10,00' },
  { name: 'Anônimo', time: 'há 3 horas', amount: 'R$ 20,00' },
  { name: 'Anônimo', time: 'há 45 minutos', amount: 'R$ 100,00' },
  { name: 'Anônimo', time: 'há 12 horas', amount: 'R$ 10,00' },
  { name: 'Miriele Aparecida Pereira', time: 'há 3 meses', amount: 'R$ 100,00' },
  { name: 'Anônimo', time: 'há 2 meses', amount: 'R$ 20,00' },
  { name: 'Ana carolina da Silva Luersen', time: 'há 3 meses', amount: 'R$ 15,00' },
  { name: 'Rodrigo K Kondo', time: 'há 2 meses', amount: 'R$ 50,00' },
  { name: 'Marinez Martinello', time: 'há 3 meses', amount: 'R$ 25,00' },
  { name: 'Anônimo', time: 'há 2 meses', amount: 'R$ 30,00' },
  { name: 'Alice', time: 'há 3 meses', amount: 'R$ 41,00' },
  { name: 'Anônimo', time: 'há 2 meses', amount: 'R$ 10,00' },
  { name: 'Emille de Sousa Vasconcelos Soares', time: 'há 3 meses', amount: 'R$ 10,00' },
  { name: 'Thainá', time: 'há 2 meses', amount: 'R$ 30,00' },
  { name: 'Debora Lemes Tavares', time: 'há 3 meses', amount: 'R$ 500,00' },
  { name: 'Rafaela da Silva Souza', time: 'há 2 meses', amount: 'R$ 10,00' },
  { name: 'Maiara Thais Marcanzoni', time: 'há 3 meses', amount: 'R$ 10,00' },
  { name: 'Anônimo', time: 'há 2 meses', amount: 'R$ 30,00' },
  { name: 'Anônimo', time: 'há 3 meses', amount: 'R$ 30,00' },
  { name: 'David Juan dos Santos', time: 'há 2 meses', amount: 'R$ 10,00' },
  { name: 'Anônimo', time: 'há 3 meses', amount: 'R$ 10,00' },
  { name: 'Priscila Da Silva Oliveira', time: 'há 2 meses', amount: 'R$ 30,00' },
  { name: 'Matheus Cerqueira Ribeiro', time: 'há 3 meses', amount: 'R$ 100,00' },
  { name: 'Rafael Mazzeo', time: 'há 2 meses', amount: 'R$ 30,00' },
  { name: 'Lorena Anunciação', time: 'há 3 meses', amount: 'R$ 30,00' },
  { name: 'Marcela Soares', time: 'há 2 meses', amount: 'R$ 30,00' },
  { name: 'Anônimo', time: 'há 3 meses', amount: 'R$ 10,00' },
  { name: 'Anônimo', time: 'há 2 meses', amount: 'R$ 100,00' },
  { name: 'Gabriela Rodrigues', time: 'há 3 meses', amount: 'R$ 50,00' },
  { name: 'Anônimo', time: 'há 2 meses', amount: 'R$ 200,00' },
  { name: 'Vitor Sartoro', time: 'há 3 meses', amount: 'R$ 50,00' },
  { name: 'Guilherme', time: 'há 2 meses', amount: 'R$ 50,00' },
  { name: 'Clara Mazini', time: 'há 3 meses', amount: 'R$ 30,00' },
  { name: 'Anônimo', time: 'há 2 meses', amount: 'R$ 200,00' },
  { name: 'Anônimo', time: 'há 3 meses', amount: 'R$ 23,00' },
  { name: 'Anônimo', time: 'há 2 meses', amount: 'R$ 400,00' },
  { name: 'Anônimo', time: 'há 3 meses', amount: 'R$ 50,00' },
  { name: 'Anônimo', time: 'há 2 meses', amount: 'R$ 30,00' },
  { name: 'Hani Alkazaal', time: 'há 3 meses', amount: 'R$ 50,00' },
  { name: 'Fabiola Gomes Farias', time: 'há 2 meses', amount: 'R$ 50,00' },
  { name: 'Maisa santana', time: 'há 3 meses', amount: 'R$ 20,00' },
  { name: 'Edna', time: 'há 2 meses', amount: 'R$ 100,00' },
  { name: 'Kézia G', time: 'há 3 meses', amount: 'R$ 50,00' },
  { name: 'Anônimo', time: 'há 2 meses', amount: 'R$ 10,00' },
  { name: 'Anônimo', time: 'há 3 meses', amount: 'R$ 10,00' },
  { name: 'Anônimo', time: 'há 2 meses', amount: 'R$ 100,00' },
  { name: 'Anônimo', time: 'há 3 meses', amount: 'R$ 10,00' },
  { name: 'Anônimo', time: 'há 2 meses', amount: 'R$ 11,00' },
  { name: 'Anônimo', time: 'há 3 meses', amount: 'R$ 50,00' },
  { name: 'Anônimo', time: 'há 2 meses', amount: 'R$ 30,00' },
  { name: 'Maria Taiana Vitorino dos Santos', time: 'há 3 meses', amount: 'R$ 10,00' },
  { name: 'David Juan dos Santos', time: 'há 2 meses', amount: 'R$ 10,00' },
  { name: 'Ingred Queiroz Souza', time: 'há 3 meses', amount: 'R$ 25,00' },
  { name: 'Anônimo', time: 'há 3 meses', amount: 'R$ 10,00' },
  { name: 'LORENNA MOURA', time: 'há 2 meses', amount: 'R$ 100,00' },
  { name: 'Letizia de Almeida Miranda', time: 'há 3 meses', amount: 'R$ 100,00' },
];

export const BUDGET_ITEMS = [
  { title: 'Exames Oncológicos Particulares', subtitle: '(Ressonâncias, biópsias e exames de alto custo)', value: 'R$ 18.000' },
  { title: 'Alimentação Especial e Rigorosa', subtitle: '(Dieta específica para suportar a quimioterapia)', value: 'R$ 15.000' },
  { title: 'Transporte Intermunicipal Seguro', subtitle: '(Deslocamento contínuo de Luziânia para os hospitais)', value: 'R$ 12.000' },
  { title: 'Medicamentos de Alto Custo', subtitle: '(Suporte imunológico e alívio dos efeitos colaterais)', value: 'R$ 10.000' },
  { title: 'Apoio Emergencial Familiar', subtitle: '(Custos básicos para focarmos 100% no tratamento)', value: 'R$ 5.000' },
];
